
package telasNovas;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;


public class CadastroHospedes extends javax.swing.JFrame {

   
    public CadastroHospedes() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    JDesktopPane hospede = null;

    CadastroHospedes(JDesktopPane jDesktopPane2) {
        this();
        hospede = jDesktopPane2;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneCadastroHosp = new javax.swing.JDesktopPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldNomeHosp = new javax.swing.JTextField();
        jTextFieldNasciHosp = new javax.swing.JTextField();
        jTextFieldCPFHosp = new javax.swing.JTextField();
        jTextFieldFoneHosp = new javax.swing.JTextField();
        jTextFieldEmailHosp = new javax.swing.JTextField();
        jTextFieldPaisHosp = new javax.swing.JTextField();
        jTextFieldEsCiHosp = new javax.swing.JTextField();
        jTextFieldCepHosp = new javax.swing.JTextField();
        jTextFieldLogHosp = new javax.swing.JTextField();
        jTextFieldNumHosp = new javax.swing.JTextField();
        jTextFieldCompleHosp = new javax.swing.JTextField();
        jButtonSlavarHosp = new javax.swing.JButton();
        jButtonAlterarHosp = new javax.swing.JButton();
        jButtonConsultarHosp = new javax.swing.JButton();
        jButtonExcluirHosp = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPaneCadastroHosp.setBackground(new java.awt.Color(255, 51, 51));
        jDesktopPaneCadastroHosp.setForeground(new java.awt.Color(240, 240, 240));

        jLabel14.setBackground(new java.awt.Color(255, 51, 51));
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Logradouro:");

        jLabel15.setBackground(new java.awt.Color(255, 51, 51));
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Estado/Cidade:");

        jLabel16.setBackground(new java.awt.Color(255, 51, 51));
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("País:");

        jLabel17.setBackground(new java.awt.Color(255, 51, 51));
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Número:");

        jLabel18.setBackground(new java.awt.Color(255, 51, 51));
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Complemento:");

        jLabel19.setBackground(new java.awt.Color(255, 51, 51));
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Nome Completo:");

        jLabel20.setBackground(new java.awt.Color(255, 51, 51));
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Data/Nascimento:");

        jLabel21.setBackground(new java.awt.Color(255, 51, 51));
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Telefone:");

        jLabel22.setBackground(new java.awt.Color(255, 51, 51));
        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("CPF:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Cadastro de Hóspedes:");

        jLabel24.setBackground(new java.awt.Color(255, 51, 51));
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("E-mail:");

        jLabel25.setBackground(new java.awt.Color(255, 51, 51));
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("CEP:");

        jButtonSlavarHosp.setText("Salvar");

        jButtonAlterarHosp.setText("Alterar");

        jButtonConsultarHosp.setText("Consultar");

        jButtonExcluirHosp.setText("Excluir");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneCadastroHospLayout = new javax.swing.GroupLayout(jDesktopPaneCadastroHosp);
        jDesktopPaneCadastroHosp.setLayout(jDesktopPaneCadastroHospLayout);
        jDesktopPaneCadastroHospLayout.setHorizontalGroup(
            jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel23))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)
                        .addGap(321, 321, 321)
                        .addComponent(jLabel20))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldNomeHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldNasciHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel22))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldFoneHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCPFHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel15)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel24))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldPaisHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEsCiHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextFieldEmailHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel18)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel25)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel17))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldLogHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCompleHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextFieldCepHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldNumHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButtonSlavarHosp)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonConsultarHosp)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonAlterarHosp)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonExcluirHosp)))
                .addGap(61, 61, 61))
        );
        jDesktopPaneCadastroHospLayout.setVerticalGroup(
            jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jButtonVoltar))
                .addGap(20, 20, 20)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNasciHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(6, 6, 6)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFoneHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCPFHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel24))
                .addGap(4, 4, 4)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPaisHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEsCiHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldEmailHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addGroup(jDesktopPaneCadastroHospLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel25))
                    .addComponent(jLabel17))
                .addGap(4, 4, 4)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLogHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompleHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCepHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jDesktopPaneCadastroHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSlavarHosp)
                    .addComponent(jButtonConsultarHosp)
                    .addComponent(jButtonAlterarHosp)
                    .addComponent(jButtonExcluirHosp))
                .addContainerGap())
        );
        jDesktopPaneCadastroHosp.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldNomeHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldNasciHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldCPFHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldFoneHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldEmailHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldPaisHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldEsCiHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldCepHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldLogHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldNumHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jTextFieldCompleHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jButtonSlavarHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jButtonAlterarHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jButtonConsultarHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jButtonExcluirHosp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneCadastroHosp.setLayer(jButtonVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCadastroHosp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCadastroHosp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        try {
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroHospedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarHosp;
    private javax.swing.JButton jButtonConsultarHosp;
    private javax.swing.JButton jButtonExcluirHosp;
    private javax.swing.JButton jButtonSlavarHosp;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JDesktopPane jDesktopPaneCadastroHosp;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JTextField jTextFieldCPFHosp;
    private javax.swing.JTextField jTextFieldCepHosp;
    private javax.swing.JTextField jTextFieldCompleHosp;
    private javax.swing.JTextField jTextFieldEmailHosp;
    private javax.swing.JTextField jTextFieldEsCiHosp;
    private javax.swing.JTextField jTextFieldFoneHosp;
    private javax.swing.JTextField jTextFieldLogHosp;
    private javax.swing.JTextField jTextFieldNasciHosp;
    private javax.swing.JTextField jTextFieldNomeHosp;
    private javax.swing.JTextField jTextFieldNumHosp;
    private javax.swing.JTextField jTextFieldPaisHosp;
    // End of variables declaration//GEN-END:variables
}
