package telasNovas;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

public class Quartos extends javax.swing.JFrame {

    public Quartos() {
        initComponents();
    }
    JDesktopPane quart = null;

    Quartos(JButton jButtonQuartos) {
        this();
        JDesktopPane jDesktopPane2 = null;
        quart = jDesktopPane2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneQuarto = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldNumQuart = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAndarQuart = new javax.swing.JFormattedTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldCapacitQuart = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalvarQuart = new javax.swing.JButton();
        jButtonAlterarQuart = new javax.swing.JButton();
        jButtonConsultarQuart = new javax.swing.JButton();
        jButtonExcluirQuart = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPaneQuarto.setBackground(new java.awt.Color(255, 0, 0));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Capacidade:");

        jRadioButton7.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton7.setText("Apto Luxo s/ varanda");

        jRadioButton6.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton6.setText("Apto Luxo c/ varanda");

        jRadioButton5.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton5.setText("Apto Premiere");

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Numero do quarto:");

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Tipo de quarto:");

        jFormattedTextFieldNumQuart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextFieldAndarQuart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jRadioButton3.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton3.setText("Suíte PNE");

        jRadioButton4.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton4.setText("Apto Executivo");

        jRadioButton1.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton1.setText("Suíte Master");

        jRadioButton2.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton2.setText("Suíte Executiva");

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Andar:");

        jFormattedTextFieldCapacitQuart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Cadastro de Quarto:");

        jButtonSalvarQuart.setText("Salvar");

        jButtonAlterarQuart.setText("Alterar");

        jButtonConsultarQuart.setText("Consultar");

        jButtonExcluirQuart.setText("Excluir");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneQuartoLayout = new javax.swing.GroupLayout(jDesktopPaneQuarto);
        jDesktopPaneQuarto.setLayout(jDesktopPaneQuartoLayout);
        jDesktopPaneQuartoLayout.setHorizontalGroup(
            jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneQuartoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldNumQuart, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldCapacitQuart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldAndarQuart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton6))
                                    .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                        .addComponent(jRadioButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton3)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1))
                            .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButtonSalvarQuart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConsultarQuart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAlterarQuart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluirQuart)))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPaneQuartoLayout.setVerticalGroup(
            jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneQuartoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonVoltar))
                .addGap(31, 31, 31)
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNumQuart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCapacitQuart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldAndarQuart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton6))
                .addGap(19, 19, 19)
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jDesktopPaneQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarQuart)
                    .addComponent(jButtonConsultarQuart)
                    .addComponent(jButtonAlterarQuart)
                    .addComponent(jButtonExcluirQuart))
                .addContainerGap())
        );
        jDesktopPaneQuarto.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jFormattedTextFieldNumQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jFormattedTextFieldAndarQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jFormattedTextFieldCapacitQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jButtonSalvarQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jButtonAlterarQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jButtonConsultarQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jButtonExcluirQuart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneQuarto.setLayer(jButtonVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneQuarto, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneQuarto)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        try {
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quartos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarQuart;
    private javax.swing.JButton jButtonConsultarQuart;
    private javax.swing.JButton jButtonExcluirQuart;
    private javax.swing.JButton jButtonSalvarQuart;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JDesktopPane jDesktopPaneQuarto;
    private javax.swing.JFormattedTextField jFormattedTextFieldAndarQuart;
    private javax.swing.JFormattedTextField jFormattedTextFieldCapacitQuart;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumQuart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
}
